<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>unlose.McpServer</AssemblyName>
    <ApplicationIcon>..\Unlose.UI\Resources\unlose.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Unlose.Core\Unlose.Core.csproj" />
  </ItemGroup>

</Project>